language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "MRlg7XGfQZorcFbiQEzkxa0rd5XbhUP2gsRmbD3ePE35+NZu4A56qVCcHELEygAH7T5a7GGTk2nHR+arbBBKAVjmnS3qwf+Cz2RlOrKoSd5gHkHsSZohSoStj9SqqiaKHZ/j3G2OG7VmuL1AJVZQO40kwZqQkq9Fme39qdbkZKMJltkHFLGc3fMNkxp51rFMfcN3d3MhufNJMNLdp7+IJJpJFoYTeGGDn0EAzRyeiegdUqFEq7nzwDI41BHReFEIPApUjICyph2wyiwmSbW9MMi7yYZ+ZeW8PDDWUoBX7z9WLEjmP5Ep1fj+g80A9xSB+/MGnHRh1F+VkbHoYR4AUZN+5YJr/9wl2JWky11W74z2/uWjfJKCSg/dcSl7wCeWIqmvvMrqRj4QEGQZicZplU9JA2m5GMDdnoogQCyaRlhCP0BWb5UIxPqswWj8/YdaJa3M2w7re5uyacBsPG2d3sOGlqh1X0tpAvcRVBDmGl4rDr8bxktVWlv3L4AdKRF9WYLL8DUBzrUBgRQjML3kc7V7xtIlPmZU8N2bhvR3MAVgx8Z5TFtMAVJ0zS2WphgO+v3IKjPb9FefAl7sCgFFGa8jrVo6j4J33bMUQ43cwKzScIGi0PWU4eDRorVV0A3F41juuhlFjJWRDmiJGMkz2MPAZ14MUk9yRQIeURpGAt0="
